version: '3.8'
services:

  database:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: dbuser
      POSTGRES_DB: codeconvivial
    ports:
      - 5432:5432
    volumes:
      - codeconvivial_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbuser -d codeconvivial"]
      interval: 5s
      timeout: 5s
      retries: 5


  backend:
    build: .
    container_name: backend
    ports:
      - 8080:8080
    depends_on:
      database:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/codeconvivial
    volumes:
      - ./src:/app/src
      #volume property mounts the maven_cache volume to cache the mvn dependencies in the /root/m2 dir
      - maven_cache:/root/.m2

volumes:
  codeconvivial_db:
    name: codeconvivial_db
   # have created this volume so that it gets a persistent storage location which can be shared across multiple containers. Over here
   # the purpose of the maven_cache volume is to cache the mvn dependencies so they can be reused across the container runs 
  maven_cache: 
    name: maven_cache